name: Jekyll site CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.6.5'

    - name: Install dependencies
      run: bundle install

    - name: Build Jekyll site
      run: bundle exec jekyll build

    - name: Deploy via FTP
      env:
        FTP_HOST: ${{ secrets.FTP_HOST }}
        FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
      run: |
        lftp -c "
        open -u $FTP_USERNAME,$FTP_PASSWORD $FTP_HOST;
        mirror -R ./_site /path/on/server;
        bye
        "
